/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : Cpu.C
**
**     Project   : CtrlCam
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : MC68HC908GP32_44
**
**     Version   : Bean 01.065, Driver 01.17, CPU db: 2.89.000
**
**     Compiler  : Metrowerks HC08 C Compiler
**
**     Date/Time : 9/15/miércoles, 10:49
**
**     Abstract  :
**
**         This bean "MC68HC908GP32_44" implements properties, methods,
**         and events of the CPU.
**
**     Settings  :
**
**         Clock setting
**             External clock      : 0.032768 MHz
**             CPU mode selection  : User mode
**             Initialization interrupt priority : 1
**             LVI module          : no
**
**         Speed modes
**             High speed clock    : Main clock frequency / 1
**             Internal bus clock  : 4.9152 MHz
**             Low speed mode      : Disabled
**             Slow speed mode     : Disabled
**
**     Contents  :
**
**         GetSpeedMode - byte Cpu_GetSpeedMode(void);
**         EnableInt    - void Cpu_EnableInt(void);
**         DisableInt   - void Cpu_DisableInt(void);
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/

/* MODULE Cpu. */

#include "LED_VAL.h"
#include "SERIE.h"
#include "ENABLE_LED1.h"
#include "ENABLE_LED2.h"
#include "Timer.h"
#include "Flash.h"
#include "DERECHA.h"
#include "IZQUIERDA.h"
#include "ARRIBA.h"
#include "ABAJO.h"
#include "FOCOMAS.h"
#include "FOCOMENOS.h"
#include "ZOOMMAS.h"
#include "ZOOMMENOS.h"
#include "Seleccion.h"
#include "Teclado.h"
#include "Inhr2.h"
#include "Inhr3.h"
#include "Inhr4.h"
#include "Inhr5.h"
#include "Inhr6.h"
#include "Inhr7.h"
#include "Inhr8.h"
#include "Inhr9.h"
#include "JoistickAction.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  255


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR register */
byte CpuMode = HIGH_SPEED;             /* Current speed mode */


/*
** ===================================================================
**     Method      :  Cpu_Interrupt (bean MC68HC908GP32_44)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
__interrupt void Cpu_Interrupt(void)
{
}

/*
** ===================================================================
**     Method      :  Cpu_SWIInterrupt (bean MC68HC908GP32_44)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
__interrupt void Cpu_SWIInterrupt(void)
{
  Cpu_OnSwINT();                       /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (bean MC68HC908GP32_44)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (bean MC68HC908GP32_44)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_GetSpeedMode (bean MC68HC908GP32_44)
**
**     Description :
**         Get current speed mode
**     Parameters  : None
**     Returns     :
**         ---             - Speed mode (HIGH_SPEED, LOW_SPEED,
**                           SLOW_SPEED)
** ===================================================================
*/
byte Cpu_GetSpeedMode(void)
{
  return CpuMode;                      /* Result the actual cpu mode */
}



/*
** ===================================================================
**     Method      :  _EntryPoint (bean MC68HC908GP32_44)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /*** ### MC68HC908GP32_44 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* System clock initialization */
  /* CONFIG1: COPRS=0,LVISTOP=0,LVIRSTD=0,LVIPWRD=1,LVI5OR3=0,SSREC=0,STOP=0,COPD=1 */
  CONFIG1 = 17;                        /* Set the CONFIG1 register */
  /* CONFIG2: ??=0,??=0,??=0,??=0,??=0,??=0,OSCSTOPENB=0,SCIBDSRC=1 */
  CONFIG2 = 1;                         /* Set the CONFIG2 register */
  PCTL_BCS = 0;                        /* Select clock source from XTAL */
  PCTL_PLLON = 0;                      /* Disable the PLL */
  PMS = 600;                           /* Set the multiplier */
  PMRS = 128;                          /* Set the range select */
  PCTL = 0;
  PCTL_VPR = 2;
  PBWC = 128;                          /* Select the operating modes */
  PCTL_PLLON = 1;                      /* Enable the PLL */
  while(!PBWC_LOCK);                   /* Wait */
  PCTL_BCS = 1;                        /* Select clock source from PLL */
  __asm("nop");
  __asm("nop");
  /*** End of PE initialization code after reset ***/

  __asm   jmp _Startup ;               /* Jump to C startup code */

}

/*
** ===================================================================
**     Method      :  PE_low_level_init (bean MC68HC908GP32_44)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
/* PTCPUE: PTCPUE6=0,PTCPUE5=0,PTCPUE4=0,PTCPUE3=0,PTCPUE2=0,PTCPUE1=0,PTCPUE0=0 */
  output( PTCPUE, input( PTCPUE ) & ~127 );
/* PTC: PTC6=1,PTC5=1,PTC4=1,PTC3=0,PTC2=0,PTC1=0,PTC0=0 */
  output( PTC, input( PTC ) & ~15 | 112 );
/* DDRC: DDRC6=1,DDRC5=1,DDRC4=1,DDRC3=1,DDRC2=1,DDRC1=1,DDRC0=1 */
  output( DDRC, input( DDRC ) | 127 );
/* PTB: PTB7=0,PTB6=0,PTB5=0,PTB4=0,PTB3=0,PTB2=0,PTB1=0,PTB0=0 */
  output( PTB, 0 );
/* DDRB: DDRB7=1,DDRB6=1,DDRB5=1,DDRB4=1,DDRB3=1,DDRB2=1,DDRB1=1,DDRB0=1 */
  output( DDRB, 255 );
/* PTDPUE: PTDPUE7=1,PTDPUE3=0,PTDPUE2=0,PTDPUE1=0,PTDPUE0=0 */
  output( PTDPUE, input( PTDPUE ) & ~15 | 128 );
/* PTD: PTD3=0,PTD2=0,PTD1=0,PTD0=0 */
  output( PTD, input( PTD ) & ~15 );
/* DDRD: DDRD7=0,DDRD3=1,DDRD2=1,DDRD1=1,DDRD0=1 */
  output( DDRD, input( DDRD ) & ~128 | 15 );
/* PTAPUE: PTAPUE7=1,PTAPUE6=1,PTAPUE5=1,PTAPUE4=1,PTAPUE3=0,PTAPUE2=0,PTAPUE1=0,PTAPUE0=0 */
  output( PTAPUE, 240 );
/* PTA: PTA3=0,PTA2=0,PTA1=0,PTA0=0 */
  output( PTA, input( PTA ) & ~15 );
/* DDRA: DDRA7=0,DDRA6=0,DDRA5=0,DDRA4=0,DDRA3=1,DDRA2=1,DDRA1=1,DDRA0=1 */
  output( DDRA, 15 );
  /* ### MC68HC908GP32_44 "Cpu" init code ... */
  /* ### Asynchro serial "SERIE" init code ... */
  /* DDRE: DDRE1=0 */
  DDRE &= ~2;
  /* PTE: PTE0=1 */
  PTE |= 1;
  /* DDRE: DDRE0=1 */
  DDRE |= 1;
  SERIE_Init();
  /* ### TimerInt "Timer" init code ... */
  Timer_Init();
  /* ###  "Teclado" init code ... */
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
  __EI();                              /* Enable interrupts */
}

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.23 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/
