/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : Inhr1.C
**
**     Project   : ctrlcam
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : ExtInt
**
**     Version   : Bean 02.016, Driver 01.10, CPU db: 2.87.041
**
**     Compiler  : Metrowerks HC08 C Compiler V-5.0.13
**
**     Date/Time : 1/23/viernes, 12:30
**
**     Abstract  :
**
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**
**     Settings  :
**
**         Interrupt name              : INT_IRQ
**         User handling procedure     : Inhr1_OnInterrupt
**
**         Used pin                    : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       11            |  IRQ
**             ----------------------------------------------------
**
**         Signal edge/level           : falling
**         Initial state               : Disabled
**
**         Edge register               : INTSCR    [29]
**         Enable register             : INTSCR    [29]
**         Request register            : INTSCR    [29]
**
**
**     Contents  :
**
**         Enable  - void Inhr1_Enable(void);
**         Disable - void Inhr1_Disable(void);
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/

#include "Inhr1.h"

/*Including shared modules, which are used for all project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Teclado.h"
#include "Cpu.h"

/*
** ===================================================================
**     Method      :  Inhr1_Enable (bean ExtInt)
**
**     Description :
**         Enable the bean - the external events are accepted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Inhr1_Enable(void)
{
  INTSCR_ACK = 1;
  INTSCR_IMASK = 0;
}

/*
** ===================================================================
**     Method      :  Inhr1_Disable (bean ExtInt)
**
**     Description :
**         Disable the bean - the external events are not accepted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Inhr1_Disable(void)
{
  INTSCR_IMASK = 1;
}

/*
** ===================================================================
**     Method      :  Inhr1_Interrupt (bean ExtInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
__interrupt void Inhr1_Interrupt(void)
{
  Inhr1_OnInterrupt();
}

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 02.89 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/
