/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : Teclado.C
**
**     Project   : CtrlCam
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : KeyboardMatrix
**
**     Version   : Bean 01.001, Driver 01.12, CPU db: 2.89.000
**
**     Compiler  : Metrowerks HC08 C Compiler
**
**     Date/Time : 9/15/miércoles, 10:49
**
**     Abstract  :
**
**
**
**     Settings  :
**
**
**
**     Contents  :
**
**         Enable     - byte Teclado_Enable(void);
**         Disable    - byte Teclado_Disable(void);
**         GetKeyCode - byte Teclado_GetKeyCode(word *key);
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/


/* MODULE Teclado. */
#pragma MESSAGE DISABLE C5660 /* WARNING C5660: Removed dead code */

#include "LED_VAL.h"
#include "SERIE.h"
#include "ENABLE_LED1.h"
#include "ENABLE_LED2.h"
#include "Timer.h"
#include "Flash.h"
#include "DERECHA.h"
#include "IZQUIERDA.h"
#include "ARRIBA.h"
#include "ABAJO.h"
#include "FOCOMAS.h"
#include "FOCOMENOS.h"
#include "ZOOMMAS.h"
#include "ZOOMMENOS.h"
#include "Seleccion.h"
#include "Teclado.h"
#include "Inhr2.h"
#include "Inhr3.h"
#include "Inhr4.h"
#include "Inhr5.h"
#include "Inhr6.h"
#include "Inhr7.h"
#include "Inhr8.h"
#include "Inhr9.h"
#include "JoistickAction.h"
#include "Teclado.h"

byte EnUser;
/*
** ===================================================================
**     Method      :  Teclado_ScanKeyboard (bean KeyboardMatrix)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static word ScanKeyboard(void)
{
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
}
/*
** ===================================================================
**     Method      :  Teclado_GetKeyCode (bean KeyboardMatrix)
**
**     Description :
**         Method gets code for pressed key
**     Parameters  :
**         NAME            - DESCRIPTION
**       * key             - Keycode
**     Returns     :
**         ---             - Error
** ===================================================================
*/
byte Teclado_GetKeyCode(word *key)
{
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
}

/*
** ===================================================================
**     Method      :  Teclado_Init (bean KeyboardMatrix)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void Teclado_Init(void)
{
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
}

/*
** ===================================================================
**     Method      :  Teclado_Disable (bean KeyboardMatrix)
**
**     Description :
**         Disable A/D convertor bean
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Teclado_Disable(void)
{
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
}

/*
** ===================================================================
**     Method      :  Teclado_Enable (bean KeyboardMatrix)
**
**     Description :
**         Enable A/D convertor bean
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Teclado_Enable(void)
{
/*
 #####  Here will be code here if you have a full registered version  #####
*/
 
}

/* END Teclado. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.23 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/

