/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : Cpu.C
**
**     Project   : CtrlCam
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : MC68HC908GP32_44
**
**     Version   : Bean 01.065, Driver 01.17, CPU db: 2.89.000
**
**     Compiler  : Metrowerks HC08 C Compiler
**
**     Date/Time : 9/15/miércoles, 10:49
**
**     Abstract  :
**
**         This bean "MC68HC908GP32_44" implements properties, methods,
**         and events of the CPU.
**
**     Settings  :
**
**         Clock setting
**             External clock      : 0.032768 MHz
**             CPU mode selection  : User mode
**             Initialization interrupt priority : 1
**             LVI module          : no
**
**         Speed modes
**             High speed clock    : Main clock frequency / 1
**             Internal bus clock  : 4.9152 MHz
**             Low speed mode      : Disabled
**             Slow speed mode     : Disabled
**
**     Contents  :
**
**         GetSpeedMode - byte Cpu_GetSpeedMode(void);
**         EnableInt    - void Cpu_EnableInt(void);
**         DisableInt   - void Cpu_DisableInt(void);
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/


#include "Cpu.h"
#include "LED_VAL.h"
#include "SERIE.h"
#include "ENABLE_LED1.h"
#include "ENABLE_LED2.h"
#include "Timer.h"
#include "Flash.h"
#include "DERECHA.h"
#include "IZQUIERDA.h"
#include "ARRIBA.h"
#include "ABAJO.h"
#include "FOCOMAS.h"
#include "FOCOMENOS.h"
#include "ZOOMMAS.h"
#include "ZOOMMENOS.h"
#include "Seleccion.h"
#include "Teclado.h"
#include "Inhr2.h"
#include "Inhr3.h"
#include "Inhr4.h"
#include "Inhr5.h"
#include "Inhr6.h"
#include "Inhr7.h"
#include "Inhr8.h"
#include "Inhr9.h"
#include "JoistickAction.h"
extern void _EntryPoint(void);

void (* const _vect[])() @0xFFDC = {   // Interrupt table
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           SERIE_InterruptTx,
           SERIE_InterruptRx,
           SERIE_InterruptError,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Timer_Interrupt,
           Cpu_Interrupt,
           Cpu_Interrupt,
           Cpu_SWIInterrupt,
           _EntryPoint
   };
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.23 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/
